DataSematics/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace DataSematics.Controllers
{
    [FilterConfig.SessionAuthorize]
    public class AboutController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

DataSematics/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Web.Helpers;
using BussinesLogic;
using Models;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using System.Web.Mvc.Html;
//using System.Web.Helpers;
using System.Json;
using System.Web.Script.Serialization;
using System.IO;
using pegu.Controllers;

namespace DataSematics.Controllers
{
    [FilterConfig.SessionAuthorize]
    public class DashboardController : Controller
    {
        public ActionResult Index()
        {
            Account_BLL obll = new Account_BLL();
            var odata = obll.Get_Dashboard_details(Convert.ToString(Session["User_Id"]));

            return View(odata);
        }

        public PartialViewResult DrawChart(string column,string target,int type)
        {
            try
            {
                ViewBag.Message = "Sales";
                Account_BLL obll = new Account_BLL();
                var odata = obll.Get_data_details(column, target,type);

                if (odata != null && odata.Count() > 0)
                {
                    List<d_graph_data> obj = new List<d_graph_data>();
                    foreach (var item in odata)
                    {
                        d_graph_data odatas = new d_graph_data();
                        try
                        {
                            odatas.Count = Convert.ToDecimal(item.frequency);
                        }
                        catch
                        {
                            odatas.Count = 0;
                        }
                        odatas.Product = item.bin;
                        obj.Add(odatas);
                    }
                    if (type == 1)
                    {
                        return PartialView("_BarGraph", obj.ToArray());
                    }
                    else
                    {
                        return PartialView("_Graph", obj.ToArray());
                    }
                }
                else
                {
                    return PartialView("_Graph");
                }
            }
            catch
            {
                return PartialView("_Graph");
            }
        }



        public ActionResult overlap()
        {
            Product_Purchaselist products_data = new Product_Purchaselist();
            Product_purchase_BLL productBll = new Product_purchase_BLL();
            var res = productBll.campain_list();
            products_data.content = products_data.content;
            products_data.content = res;
            return View(products_data);
        }
        public PartialViewResult Drawproduct_overlap(string campain)
        {
            
            //List<Overlap> olist = new List<Overlap>();
            //List<string> o=new List<string>();
            //o.Add("assda");
            //olist.Add(new Overlap { sets = o, size = 10, label = "asd" });
            //return PartialView("Overlap_graph", olist.ToArray());
              try
            {
                ViewBag.Message = "Sales";
                Product_purchase_BLL obll = new Product_purchase_BLL();
                var odata = obll.Product_overlap_data(campain);
               
                if (odata != null && odata.Count() > 0)
                {
                    var rows = new List<Object>();
                    List<g_overlap_graph> obj = new List<g_overlap_graph>();
                    foreach (var item in odata)
                    {
                        g_overlap_graph odatas = new g_overlap_graph();

                        odatas.sets = item.Products; 
                        odatas.label = item.Product_Label;
                        odatas.size = item.size;

                        obj.Add(odatas);

                         
                    }
                    var options = obj;
                    var serializer = new JsonSerializer();
                    var stringWriter = new StringWriter();
                    using (var writer = new JsonTextWriter(stringWriter))
                    {
                        writer.QuoteName = false;
                        serializer.Serialize(writer, options);
                    }
                    var json = stringWriter.ToString();
                    json = json.Replace("\"[", "[").Replace("]\"", "]");

                    return PartialView("Overlap_graph", json);
                     
                }
                else
                {
                    return PartialView("Overlap_graph");
                }
            }
            catch
            {
                return PartialView("Overlap_graph");
            }


        }

        public ActionResult Overlap_graph()
        {
            Product_purchase_BLL productBll = new Product_purchase_BLL();
            return View();
        }

    }
}

DataSematics/Controllers/DocumentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BussinesLogic;
using Models;
using System.Web.Helpers;

namespace DataSematics.Controllers
{
    [FilterConfig.SessionAuthorize]
    public class DocumentsController : Controller
    {
        public ActionResult Index()
        {
            SuperAdminBLL SABLL = new SuperAdminBLL();
            List<document_list> result = new List<document_list>();
            document_list records = SABLL.Document_List();

            return View(records);
        }
        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Create_Document(insert_document data)
        {
            var obj = data.Document_name;
            SuperAdminBLL SABLL = new SuperAdminBLL();
            var result = SABLL.Create_Doc(obj);
            var status = result.status;
            if (status == 1)
            {
                TempData["toaster_success"] = "Document Created Sucessfully";

            }
            else
            {
                TempData["toaster_error"] = "Document Creation Failed";
            }
            return RedirectToAction("Create");

        }

        public ActionResult Delete_Documents_type(string Id)
        {

            SuperAdminBLL oBll = new SuperAdminBLL();
            EmptyResponse status = oBll.Delete_Documents_Type(Id);
            if (status.status == 1)
            {
                TempData["toaster_success"] = "Deleted Sucessfully";

            }
            else
            {
                TempData["toaster_error"] = "Failed to delete";
            }
            return RedirectToAction("Index", "Experiment");
        }
    }
}

DataSematics/Controllers/SuperAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BussinesLogic;
using Models; 
using System.Web.Helpers;

namespace DataSematics.Controllers
{
    [FilterConfig.SessionAuthorize]
    public class SuperAdminController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult DrawChart()
        {

            var myChart = new Chart(width: 500, height: 400)
                .AddTitle("Chart Title")
                .AddSeries(
                    name: "Employee",
                    xValue: new[] { "Peter", "Andrew", "Julie", "Mary", "Dave" },
                    yValues: new[] { "2", "6", "4", "5", "3" })
              .GetBytes("png");
            return File(myChart, "image/bytes");

        }

        public ActionResult DrawChart1()
        {
            var chart = new Chart(width: 500, height: 400)
             .AddTitle("Success Campains")
                .AddSeries(
                            chartType: "Pie",
                            xValue: new[] { "Success", "Failure", "Processing" },
                            yValues: new[] { "60", "10", "10" })
                            .GetBytes("png");
            return File(chart, "image/bytes");
        }  
	}
}

DataSematics/Views/Shared/ClientMessage.cshtml
@{
    ViewBag.Title = "ClientMessage";
} 
<script src="~/Scripts/toaster.js"></script>
@if (TempData["toaster_success"] != null)
{
    <script>

      toastr.options = {
          "closeButton": true,
          "debug": false,
          "newestOnTop": false,
          "progressBar": true,
          "positionClass": "toast-top-right",
          "preventDuplicates": false,
          "onclick": null,
          "showDuration": "300",
          "hideDuration": "1000",
          "timeOut": "5000",
          "extendedTimeOut": "1000",
          "showEasing": "swing",
          "hideEasing": "linear",
          "showMethod": "fadeIn",
          "hideMethod": "fadeOut"
      };

      toastr.success("", "@TempData["toaster_success"]");
    </script>
}
else if (TempData["toaster_warning"] != null)
{
    <script>

      toastr.options = {
          "closeButton": true,
          "debug": false,
          "newestOnTop": false,
          "progressBar": true,
          "positionClass": "toast-top-right",
          "preventDuplicates": false,
          "onclick": null,
          "showDuration": "300",
          "hideDuration": "1000",
          "timeOut": "5000",
          "extendedTimeOut": "1000",
          "showEasing": "swing",
          "hideEasing": "linear",
          "showMethod": "fadeIn",
          "hideMethod": "fadeOut"
      };

      toastr.warning("", "@TempData["toaster_warning"]");
    </script>
}
else if (TempData["toaster_error"] != null)
{
    <script>

      toastr.options = {
          "closeButton": true,
          "debug": false,
          "newestOnTop": false,
          "progressBar": true,
          "positionClass": "toast-top-right",
          "preventDuplicates": false,
          "onclick": null,
          "showDuration": "300",
          "hideDuration": "1000",
          "timeOut": "5000",
          "extendedTimeOut": "1000",
          "showEasing": "swing",
          "hideEasing": "linear",
          "showMethod": "fadeIn",
          "hideMethod": "fadeOut"
      };

      toastr.error("", "@TempData["toaster_error"]");
    </script>
}
 

DataSematics/Views/Shared/_Super_admin_layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>Predicto</title>
    <link rel="shortcut icon" href="">
    <meta name="keywords" content="DataSematics" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    @Styles.Render("~/Content/css")

</head>
<body class="nav-md">
    <div class="container body">
        <div class="main_container">
            <div class="col-md-3 left_col">
                <div class="left_col scroll-view">
                    <div class="navbar nav_title" style="border: 0;">
                        <a href='@Url.Action("Index", "Dashboard")' class="site_title">
                            <span>Predicto</span>
                        </a>
                    </div>
                    <div class="clearfix" style="border-bottom: solid 2px whitesmoke;"></div>
                    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                        @*<script src="~/Scripts/jquery-1.js"></script>*@
                        <div class="menu_section">
                            <ul class="nav side-menu">
                                <li><a href='@Url.Action("Index", "SuperAdmin")'><i class="fa fa-dashboard"></i>Dashboard</a></li>
                                <li>
                                    <a style="box-shadow:none;" class=""><i class="fa fa-bars" aria-hidden="true"></i> Department <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu ">
                                        
                                        <li><a href='@Url.Action("department_list", "Department")'><i class="fa fa-plus-circle" aria-hidden="true"></i>View</a></li>
                                        <li><a href='@Url.Action("Index", "Department")'><i class="fa fa-eye" aria-hidden="true"></i>Add</a></li>
                                    </ul>
                                </li>
                                <li>
                                    <a style="box-shadow:none;" class=""><i class="fa fa-user" aria-hidden="true"></i> Admin <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu ">

                                        <li><a href='@Url.Action("Index", "Create_Admin")'><i class="fa fa-plus-circle" aria-hidden="true"></i>View</a></li>
                                        <li><a href='@Url.Action("Create", "Create_Admin")'><i class="fa fa-eye" aria-hidden="true"></i>Add</a></li>
                                    </ul>
                                </li>         
                                

                                <li>
                                    <a style="box-shadow:none;" class=""><i class="fa fa-flask" aria-hidden="true"></i> Experiment <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu ">
                                        <li><a href='@Url.Action("Index", "Experiment")'><i class="fa fa-eye" aria-hidden="true"></i>View</a></li>
                                        <li><a href='@Url.Action("Create", "Experiment")'><i class="fa fa-plus-circle" aria-hidden="true"></i>Add</a></li>
                                    </ul>
                                </li>    
                                
                                <li>
                                    <a style="box-shadow:none;" class=""><i class="fa fa-files-o" aria-hidden="true"></i> Document Type<span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu ">
                                        <li><a href='@Url.Action("Index", "Documents")'><i class="fa fa-eye" aria-hidden="true"></i>View</a></li>
                                        <li><a href='@Url.Action("Create", "Documents")'><i class="fa fa-plus-circle" aria-hidden="true"></i>Add</a></li>
                                    </ul>
                                </li>


                                <li>
                                    <a style="box-shadow:none;" class=""><i class="fa fa-check-circle-o" aria-hidden="true"></i> Validation<span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu ">
                                        <li><a href='@Url.Action("Index", "Validation")'><i class="fa fa-eye" aria-hidden="true"></i>View</a></li>
                                        <li><a href='@Url.Action("Create", "Validation")'><i class="fa fa-plus-circle" aria-hidden="true"></i>Add</a></li>
                                    </ul>
                                </li>

                                @*<li>
                                    <a style="box-shadow:none;" href='#'><i class="fa fa-user"></i> My Profile</a>

                                </li>
                                <li>
                                    <a style="box-shadow:none;" href='#'><i class="fa fa-cog"></i> Settings</a>

                                </li>*@
                                 
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

            <div class="top_nav">
                <div class="nav_menu">
                    <nav role="navigation">
                        <ul class="nav navbar-nav pull-right head-down">
                            <div class="dropdown">
                                <a href="@Url.Action("Index", "Home")" class="btn btn-primary dropdown-toggle" type="button">
                                    Logout
                                </a>
                            </div>
                        </ul>
                        <div class="nav toggle">
                            <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                        </div>

                    </nav>
                </div>
            </div>



            @RenderBody()
        </div>
        <div class="sidebar-footer hidden-xs hidden-sm">
            <a data-toggle="tooltip" data-placement="top" title="" data-original-title="Settings">
                <small>©DSPL, 2016. All Rights Reserved.</small>
            </a>

        </div>
    </div>
    <div id="custom_notifications" class="custom-notifications dsp_none">
        <ul class="list-unstyled notifications clearfix" data-tabbed_notifications="notif-group"></ul>
        <div class="clearfix"></div>
        <div id="notif-group" class="tabbed_notifications"></div>
    </div>
    @RenderPage("~/Views/Shared/ClientMessage.cshtml")
    <style>
        .nav li.current-page {
            background: rgba(255,255,255,0.05);
        }
    </style>
    <style>
        .bs-wizard {
            margin-top: 40px;
        }

        /*Form Wizard*/
        .bs-wizard {
            border-bottom: solid 1px #e0e0e0;
            padding: 0 0 10px 0;
        }

            .bs-wizard > .bs-wizard-step {
                padding: 0;
                position: relative;
            }

                .bs-wizard > .bs-wizard-step + .bs-wizard-step {
                }

                .bs-wizard > .bs-wizard-step .bs-wizard-stepnum {
                    color: #595959;
                    font-size: 16px;
                    margin-bottom: 5px;
                }

                .bs-wizard > .bs-wizard-step .bs-wizard-info {
                    color: #999;
                    font-size: 14px;
                }

                .bs-wizard > .bs-wizard-step > .bs-wizard-dot {
                    position: absolute;
                    width: 30px;
                    height: 30px;
                    display: block;
                    background: #26b99a;
                    top: 45px;
                    left: 50%;
                    margin-top: -15px;
                    margin-left: -15px;
                    border-radius: 50%;
                }

                    .bs-wizard > .bs-wizard-step > .bs-wizard-dot:after {
                        content: ' ';
                        width: 14px;
                        height: 14px;
                        background: #34495e;
                        border-radius: 50px;
                        position: absolute;
                        top: 8px;
                        left: 8px;
                    }

                .bs-wizard > .bs-wizard-step > .progress1 {
                    position: relative;
                    border-radius: 0px;
                    height: 8px;
                    box-shadow: none;
                    margin: 17px 0;
                }

                    .bs-wizard > .bs-wizard-step > .progress1 > .progress-bar {
                        width: 0px;
                        box-shadow: none;
                        background: #26b99a;
                    }

                .bs-wizard > .bs-wizard-step.complete > .progress1 > .progress-bar {
                    width: 100%;
                }

                .bs-wizard > .bs-wizard-step.active > .progress1 > .progress-bar {
                    width: 50%;
                }

                .bs-wizard > .bs-wizard-step:first-child.active > .progress1 > .progress-bar {
                    width: 0%;
                }

                .bs-wizard > .bs-wizard-step:last-child.active > .progress1 > .progress-bar {
                    width: 100%;
                }

                .bs-wizard > .bs-wizard-step.disabled > .bs-wizard-dot {
                    background-color: #f5f5f5;
                }

                    .bs-wizard > .bs-wizard-step.disabled > .bs-wizard-dot:after {
                        opacity: 0;
                    }

                .bs-wizard > .bs-wizard-step:first-child > .progress1 {
                    left: 50%;
                    width: 50%;
                }

                .bs-wizard > .bs-wizard-step:last-child > .progress1 {
                    width: 50%;
                }

                .bs-wizard > .bs-wizard-step.disabled a.bs-wizard-dot {
                    pointer-events: none;
                }

        .progress1 {
            height: 9px !important;
            margin-bottom: 0px !important;
            overflow: hidden;
            background-color: #f5f5f5;
            border-radius: 4px;
            -webkit-box-shadow: inset 0 1px 2px rgba(0,0,0,.1);
            box-shadow: inset 0 1px 2px rgba(0,0,0,.1);
        }

        .progress-bar {
            float: left;
            width: 0;
            height: 100%;
            font-size: 11px !important;
            line-height: 17px !important;
            color: #fff;
            text-align: center;
            background-color: #337ab7;
            -webkit-box-shadow: inset 0 -1px 0 rgba(0,0,0,.15);
            box-shadow: inset 0 -1px 0 rgba(0,0,0,.15);
            -webkit-transition: width .6s ease;
            -o-transition: width .6s ease;
            transition: width .6s ease;
        }

        .status_view {
            padding: 1px 1px !important;
            font-size: 10px !important;
            line-height: 0.9 !important;
            margin: 8px;
        }

        .modal-body {
            position: relative;
            padding: 15px;
            border: solid 2px white;
        }

        .modal-header {
            padding: 15px;
            border-bottom: 1px solid #e5e5e5;
            background-color: #151f2a;
            color: white;
        }

        .close {
            float: right;
            font-size: 22px;
            font-weight: 700;
            line-height: 1;
            color: #ffffff;
            text-shadow: 0 1px 0 #fff;
            filter: alpha(opacity=20);
            opacity: 1.5;
        }
    </style>

    <script src="~/Scripts/jquery.min.js"></script>
    <script src="~/Scripts/multiselect.js"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>