DataSematics/Controllers/Create_AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BussinesLogic;
using Models;

namespace DataSematics.Controllers
{
    [FilterConfig.SessionAuthorize]
    public class Create_AdminController : Controller
    {
        public ActionResult Index()
        {
            SuperAdminBLL SABLL = new SuperAdminBLL();
            Departments_data data = new Departments_data();
            data = SABLL.department_list(Session["User_Id"].ToString());

            return View(data);
        }
        public ActionResult Create()
        {
            SuperAdminBLL SABLL = new SuperAdminBLL();
            Departments_data data = new Departments_data();
            data = SABLL.department_list(Session["User_Id"].ToString());

            return View(data);
        }

        public ActionResult add_admin(Departments_data data)
        {
            Create_admin obj = new Create_admin();
            obj.department_id = data.admin_create.department_id;
            obj.user_id = data.admin_create.user_id;
            obj.password = data.admin_create.password;
            SuperAdminBLL SABLL = new SuperAdminBLL();
            var result = SABLL.Create_Admin(obj);
            var status = result.status;
            if (status == 1)
            {
                TempData["toaster_success"] = "New Admin Created Sucessfully";

            }
            else
            {
                TempData["toaster_error"] = "Admin already exist";
            }
            return RedirectToAction("Create");
            
        }

        public ActionResult View_users(string Id)
        {
            SuperAdminBLL SABLL = new SuperAdminBLL();
            User_information data = SABLL.Get_UserList(Id);

            return View(data);
        }
	}
}

DataSematics/Views/Create_Admin/Create.cshtml
@{ViewBag.Title = "SuperAdmin";
    Layout = "~/Views/Shared/_Super_admin_layout.cshtml";
}
@model Models.Departments_data
<div class="right_col" role="main">
    <div class="container-fluid">
        <br />
        <br />
        <br />
        <br />

        @using (Html.BeginForm("add_admin", "Create_Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
              
        <div class="panel pbody">

            <div class="form-title">
              <h4>  <i class="fa fa-plus-circle" aria-hidden="true"></i>&nbsp;&nbsp;Add User</h4>
            </div>
            <div class="panel-body ">
                <div class="row">
                    <div class="form-group">
                        <label class="col-md-2 control-label">User Id</label>
                        <div class="col-md-8">
                            <div class="form-group">
                                @Html.TextBoxFor(m => m.admin_create.user_id, new { @class = "form-control", @placeholder = "User Name", @required = "required" })
                                
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group">
                        <label class="col-md-2 control-label">Password</label>
                        <div class="col-md-8">
                            @Html.PasswordFor(m => m.admin_create.password, new { @class = "form-control", @placeholder = "Password", @required = "required",style= "margin-bottom: 10px;" })
                         
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="form-group">
                        <label class="col-md-2 control-label">Department</label>
                        <div class="col-md-8">
                            @Html.DropDownListFor(m => m.admin_create.department_id, new SelectList(Model.content, "Id", "name", Model.content), new { @placeholder = "Select department", @class = "form-control" })

                        </div>
                    </div>
                </div>
                <div class="form-group  col-md-12" style="position:relative;top: 13px;">
                    <span class="text-center col-md-4 col-md-offset-4">
                        <button class="btn  btn-submit btn-block btn-md" type="submit">Create User</button>
                    </span>
                </div>
            </div>

        </div>
            
        }
    </div>
</div>

<style>
    .header-line {
        position: relative;
        font-size: 1.2em;
    }
</style>

DataSematics/Views/Create_Admin/Index.cshtml
@{ViewBag.Title = "SuperAdmin";
Layout = "~/Views/Shared/_Super_admin_layout.cshtml";
}
@model Models.Departments_data
<div class="right_col" role="main">
    <div class="clearfix"></div>
    <div class="panel panel-default">
        <div class="panel-heading panelPading panelcolor" id="panelbackcolor">
            &nbsp;<i class="fa fa-users"></i>&nbsp;Departments
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_content">
                        <div class="table-responsive table-fixed col-md-12" style="overflow-y: hidden;">
                            <table class="tab-score" data-toggle="table" data-show-refresh="true" data-show-toggle="true" data-show-columns="true" data-search="true" data-select-item-name="toolbar1" data-pagination="true" data-sort-name="name" data-sort-order="desc">
                                <thead class="thd">
                                    <tr>
                                        <th class="headeralign" data-sortable="true"> User Id</th>
                                        <th class="headeralign" data-sortable="true">Description</th>

                                        <th class="headeralign" data-sortable="true">Status</th>
                                        <th class="headeralign" data-sortable="true">UserInformation</th>
                                        <th class="headeralign" data-sortable="true">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.content)
                                    {

                                        <tr>
                                            <td align="center">@item.name</td>
                                            <td align="center">@item.details</td>
                                            <td align="center" style="text-align :center" class="text-center">
                                                <span class="label label-success" align="center" style="vertical-align:middle;">Successful</span>
                                            </td>
                                            <td align="center">
                                                <button class="btn btn-default  btn-xs buttoncolor" onclick="parent.location = '@Url.Action("View_users", "Create_Admin", new { Id = item.Id })'">View</button>
                                            </td>
                                            <td align="center" style="text-align :center">
                                                <a class="btn btn-default btn-xs" href='#'> Block</a>
                                            </td>
                                            
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                        <div></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

DataSematics/Views/Create_Admin/View_users.cshtml
@{ViewBag.Title = "SuperAdmin";
Layout = "~/Views/Shared/_Super_admin_layout.cshtml";
}
@model Models.User_information
<div class="right_col" role="main">
    <div class="clearfix"></div>
    <div class="panel panel-default">
        <div class="panel-heading panelPading panelcolor" id="panelbackcolor">
            &nbsp;<i class="fa fa-users"></i>&nbsp;User Information
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_content">
                        <div class="table-responsive table-fixed col-md-12" style="overflow-y: hidden;">
                            <table class="tab-score" data-toggle="table" data-show-refresh="true" data-show-toggle="true" data-show-columns="true" data-search="true" data-select-item-name="toolbar1" data-pagination="true" data-sort-name="name" data-sort-order="desc">
                                <thead class="thd">
                                    <tr>
                                        <th class="headeralign" data-sortable="true"> User Id</th>
                                        <th class="headeralign" data-sortable="true">User Name</th>

                                        <th class="headeralign" data-sortable="true">Status</th>
 
                                        <th class="headeralign" data-sortable="true">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.content)
                                    {

                                        <tr>
                                            <td align="center">@item.user_id</td>
                                            <td align="center">@item.user_name</td>
                                            <td align="center" style="text-align :center" class="text-center">
                                                <span class="label label-success" align="center" style="vertical-align:middle;">Successful</span>
                                            </td>
                                           
                                            <td align="center" style="text-align :center">
                                                <a class="btn btn-default btn-xs" href='#'> Block</a>
                                            </td>

                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                        <div></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>